name: CI

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests-and-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-report=html

      - name: Run pip-audit security scan
        id: pip_audit
        continue-on-error: true
        run: |
          pip-audit -r requirements.txt -f json -o pip-audit.json

      - name: Scan Dockerfile with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1 commit
        continue-on-error: true
        with:
          scan-type: config
          scan-ref: .
          exit-code: "1"
          severity: HIGH,CRITICAL
          format: json
          output: trivy-report.json

      - name: Upload coverage reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/

      - name: Upload security scan report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: pip-audit.json

      - name: Upload Trivy scan report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Fail on security scan findings
        if: ${{ steps.pip_audit.outcome == 'failure' || steps.trivy_scan.outcome == 'failure' }}
        run: |
          echo "Security scans reported issues. See uploaded artifacts for details." >&2
          exit 1
